# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190319_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'EXPIRED')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.IntegerField(choices=[(0, 'LOW'), (1, 'MEDIUM'), (2, 'HIGH')], default=0),
        ),
    ]
