# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190319_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
